### ISSUE TITLE
2019 evaluation only outputs ABX with Levenshtein distance

### ISSUE THREAD

**Issue by bshall** [bootphon/zerospeech2020#1]
There seems to be a bug in the `evaluate` method for the 2019 challenge. Although the ABX scores for all the metrics are stored in `details_abx` [here](https://github.com/bootphon/zerospeech2020/blob/master/zerospeech2020/evaluation/evaluation_2019.py#L147). Only the score computed with the final metric (Levenshtein distance) is passed to the `write_scores_19` function [here](https://github.com/bootphon/zerospeech2020/blob/master/zerospeech2020/evaluation/evaluation_2019.py#L159). As a result `ABX_score` always reports the Levenshtein distance score and doesn't match `ABX_distance`.

**Comment by mmmaat** [comment]
Thanks for the report, I'm watching for a fix.
