### ISSUE TITLE
ModuleNotFoundError: No module named 'tdev2'

### ISSUE THREAD

**Issue by jasonppy** [bootphon/zerospeech2020#4]
Hi,

I wanted to evaluate a new approach on ZS2017-track2. I followed the instructions in README to setup everything, but when I run 
`zerospeech2020-evaluate 2017-track2 baseline.zip -l english -o english.json`
It says ModuleNotFoundError: `No module named 'tdev2'`

Thanks in advance!

**Comment by mmmaat** [comment]
Hi,

Thanks for reporting! Before I push something to fix that you can install tdev2 manually from [here](https://github.com/bootphon/tdev2)

**Comment by jasonppy** [comment]
Hi,

Thanks for your reply! I git cloned tdev2 in the root folder and ran `python setup.py build && python setup.py install`, but when I ran 
`python main.py 2017-track2 -l english balabala`, it says 
```
File "/path/miniconda3/lib/python3.8/site-packages/zerospeech2020-0.2-py3.8.egg/zerospeech2020/evaluation/abx.py", line 14, in <module>
    import ABXpy
ModuleNotFoundError: No module named 'ABXpy'
```

Then I did `conda install -c coml abx`, but still get the same error.

**Comment by mmmaat** [comment]
Hi,
I fixed the bug. The TDE module changed its name from `tdev2` to `tde` few months ago, by was still with the former name here... All should be working now.

**Comment by jasonppy** [comment]
Hi mmmaat,

Thanks a bunch for helping me. So I redo the whole thing started from git clone, but when I run `zerospeech2020-evaluate 2017-track2 balabala`, I got another error:
```
Traceback (most recent call last):
  File "/miniconda3/envs/zerospeech2020/bin/zerospeech2020-evaluate", line 33, in <module>
    sys.exit(load_entry_point('zerospeech2020==0.2', 'console_scripts', 'zerospeech2020-evaluate')())
  File "/miniconda3/envs/zerospeech2020/bin/zerospeech2020-evaluate", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/miniconda3/envs/zerospeech2020/lib/python3.8/importlib/metadata.py", line 504, in distribution
    return Distribution.from_name(distribution_name)
  File "/miniconda3/envs/zerospeech2020/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: zerospeech2020
```

Thanks in advance!

**Comment by mmmaat** [comment]
Hum !? Did you run the `python setup.py install` as well? If so I suspect a mess in your conda venv. You can try to delete it (`conda env remove -n zerospeech2020`) and reinstall the whole:
```
conda env create -n zerospeech2020 -f environment.yaml
conda activate zerospeech2020
python setup.py install
```

**Comment by jasonppy** [comment]
Sorry my bad, it works perfectly now!
