### ISSUE TITLE
missing meta.yaml

### ISSUE THREAD

**Issue by liu-x-p** [bootphon/zerospeech2020#5]
Sorry to bother you. I'm a student in China. I submitted my work at 12 p.m. last night, which should be 4 p.m. for you.
I have validated the folder earlier this day, so I didn't validate the zip file. After I submitted it to codalab, it got something wrong 'ERROR: Submission archive is not valid.' So I validated the file and it says the submission missing meta.yaml file, but after decompression, there will be no error. I compressed again and then still reported the error.
 Is it possible to report an error as a result? I will upload my work again, although it has timed out.
![2021-03-23 08-32-51 的屏幕截图](https://user-images.githubusercontent.com/58974386/112076658-cbd4e280-8bb5-11eb-8336-22c44d95590b.png)

**Comment by nhamilakis** [comment]
Hello, is your meta.yaml a valid yaml file containing the specified fields ? could you post the contents of it ?

**Comment by liu-x-p** [comment]
I tred&nbsp; to close the question，but my explorer can't open GitHub.&nbsp;
I found I set up one more level of directory, and now it works.&nbsp;
Thank you



---Original---
From: "Nick ***@***.***&gt;
Date: Tue, Mar 23, 2021 16:54 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [bootphon/zerospeech2020] missing meta.yaml (#5)




 
Hello, is your meta.yaml a valid yaml file containing the specified fields ? could you post the contents of it ?
